const productsArray = [
    {
        id: 1,
        name: 'iPhone X',
        description: 'This is iPhone X',
        type: 'phone',
        capacity: 64,
        price: 500,
        image: '/images/iphone-black.jpg',
    },
    {
        id: 2,
        name: 'iPhone XS',
        description: 'This is iPhone XS',
        type: 'phone',
        capacity: 128,
        price: 700,
        image: '/images/iphone-blue.jpg',
    },
    {
        id: 3,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        type: 'phone',
        capacity: 512,
        price: 1000,
        image: '/images/iphone-pink.jpg',
    },
    {
        id: 4,
        name: 'iPhone 8 Plus',
        description: 'This is iPhone X',
        type: 'phone',
        capacity: 128,
        price: 800,
        image: '/images/iphone-purple.jpg',
    },
    {
        id: 5,
        name: 'iPhone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 64,
        price: 1000,
        image: '/images/iphone-red.jpg',
    },
    {
        id: 6,
        name: 'iPhone 11 Pro Max',
        description: 'This is iPhone 11 Pro Max',
        type: 'phone',
        capacity: 128,
        price: 1700,
        image: '/images/iphone-white.jpg',
    },
]

export default productsArray
